### ISSUE TITLE
[Web - Create New Course] As a content creator, I want to create just 1 test course

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-frontend#94]
Description:
- It is not possible to create just 1, it ends up generating 4 test courses.
- After adding a new class or test to a section, the name and description of the section disappears, so it is necessary to save each action instead of saving everything at the end of editing the entire course

Solution Proposal:
Review website programming
Follow Figma Interface: https://www.figma.com/design/BCEVQYvMDrcBE9qqehr9HL/Mobile-Education-UI?node-id=3074-11005&t=JeGk2yMJe7P9aZQk-4

Bug Priority Number: 4

**Comment by Laskiri** [comment]
As the bug the PBI explains had already been fixed, we focused on making the content creation process for the course a better experience, by saving new data in state and rerendering accordingly instead of reloading the page continuously on every action to refetch data from the server, which lead to loss of unsaved data to section title and descriptions.

During sprint review a bug was discovered that made it impossible to save data right after first creating a course, as the id of the created course, wasn't properly transferred to the content creation page on creation.

**Comment by magnusklundgren** [comment]
### User Tests:

**Scenario 1: Course Creation and Data Persistence**

Steps:

- User creates a new course.
- User adds content to the course (e.g., sections, classes, tests).
- User navigates away from the course creation page and then returns.

Expected Outcomes:

- The newly created course and its associated data (title, description, content) are persisted and can be retrieved upon returning to the page.
- The user can continue editing the course without losing any data.

**Scenario 2: Data Integrity**

Steps:

- User creates a new course with multiple sections and content.
- User edits the course title or description.

Expected Outcomes:

- The changes to the course title or description are saved correctly, and the associated content remains intact.
- There are no inconsistencies or data corruption issues.

**Scenario 3: User Experience**

Steps:

- User creates a new course.

Expected Outcomes:

- The course creation process is smooth and responsive.
- The user does not encounter any unexpected errors or delays.
